

name: Setup mdBook with plugins (latest)
on:
  push:
    branches:
      - main


# https://elasticdotventures.github.io/fungiblefarm-mdbook/book/ 
jobs:
  run:
    runs-on: ubuntu-22.04
    #container: 
    #  image: ghcr.io/elasticdotventures/ff-rust-musl-builder
      #credentials:
      #  username: ${{ github.actor }}
      #  password: ${{ secrets.github_token }}    
    steps:
      - uses: actions/checkout@v3 # mount github workspace

      - uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ghcr.io
          image: elasticdotventures/ff-rust-musl-builder
          #options: -v ${{ github.workspace }}:/work -e ABC=123
          run: |
            echo "Running Script"
            /work/run-script

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-mdbook-rust
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.8'
          # mdbook-version: 'latest'

      - run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

      ## alt node js
      # https://github.com/JamesIves/github-pages-deploy-action
      #- uses: JamesIves/github-pages-deploy-action@4.1.7
      #  with:
      #    branch: gh-pages # The branch the action should deploy to.
      #    folder: . # The folder the action should deploy.

